import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

const CHANGELOG =
  'https://github.com/DigiMonk73/BTCTX-MCP/blob/main/docs/CHANGELOG.md'

/** 1.2.5:0: the 2026 draft forms preview, the phone close button, the Expenses section removed, locked dependencies; nothing for the package to migrate. */
export const current = VersionInfo.of({
  version: '1.2.5:0',
  releaseNotes: {
    en_US: `BitcoinTX 1.2.5 brings a preview of the 2026 tax forms. Until the IRS publishes the final ones, Reports offers 2026 filled in on the IRS's draft Form 8949 and Schedule D, marked "DRAFT — DO NOT FILE" on every page: use them to check your figures, never to file. The preview ends by itself on January 1, 2027; the final forms come in an update. On a phone, the panel for adding or editing a transaction now has a close button (✕). The Complete Tax Report no longer has its almost always empty "Expenses" section; spending stays in the capital gains section, and no figure changes. Every component BitcoinTX is built from is now locked to an exact, verified version. Coming from 1.2.4:0 or earlier? Set Login Credentials replaces Show Credentials and Reset Login Credentials: it makes a new password and shows it once. Your login stays; only if StartOS keeps no password for you, stop BitcoinTX and run Set Login Credentials before starting it again. Coming from 1.2.1 or earlier? After updating, open Settings > Ledger Review in BitcoinTX, and if it lists figures a recalculation would change, run Recalculate Ledger. Everything: ${CHANGELOG}`,
    es_ES: `BitcoinTX 1.2.5 trae una vista previa de los formularios fiscales de 2026. Hasta que el IRS publique los definitivos, Reports ofrece 2026 rellenado en los borradores del IRS del Form 8949 y del Schedule D, marcados con "DRAFT — DO NOT FILE" en cada página: úsalos para revisar tus cifras, nunca para presentarlos. La vista previa termina sola el 1 de enero de 2027; los formularios definitivos llegan en una actualización. En un teléfono, el panel para añadir o editar una transacción tiene ahora un botón de cierre (✕). El Complete Tax Report ya no tiene su sección "Expenses", casi siempre vacía; los gastos siguen en la sección de ganancias de capital y ninguna cifra cambia. Cada componente con el que se construye BitcoinTX está ahora fijado a una versión exacta y verificada. ¿Vienes de la 1.2.4:0 o anterior? Establecer credenciales de acceso sustituye a Mostrar credenciales y Restablecer credenciales de acceso: genera una contraseña nueva y la muestra una sola vez. Tu acceso se conserva; solo si StartOS no guarda ninguna contraseña tuya, detén BitcoinTX y ejecuta Establecer credenciales de acceso antes de volver a iniciarlo. ¿Vienes de la 1.2.1 o anterior? Tras actualizar, abre Settings > Ledger Review en BitcoinTX y, si muestra cifras que un recálculo cambiaría, ejecuta Recalcular el libro contable. Todo: ${CHANGELOG}`,
    de_DE: `BitcoinTX 1.2.5 bringt eine Vorschau der Steuerformulare für 2026. Bis der IRS die endgültigen veröffentlicht, bietet Reports 2026 an, ausgefüllt auf den Entwürfen des IRS für Form 8949 und Schedule D, auf jeder Seite mit "DRAFT — DO NOT FILE" markiert: Nutze sie, um deine Zahlen zu prüfen, niemals zur Abgabe. Die Vorschau endet von selbst am 1. Januar 2027; die endgültigen Formulare kommen mit einem Update. Auf dem Handy hat das Feld zum Hinzufügen oder Bearbeiten einer Transaktion jetzt eine Schließen-Schaltfläche (✕). Der Complete Tax Report hat keinen fast immer leeren Abschnitt "Expenses" mehr; Ausgaben stehen weiter im Abschnitt Kapitalgewinne, und keine Zahl ändert sich. Jeder Baustein, aus dem BitcoinTX gebaut wird, ist jetzt auf eine genaue, geprüfte Version festgelegt. Du kommst von 1.2.4:0 oder älter? Zugangsdaten festlegen ersetzt Zugangsdaten anzeigen und Zugangsdaten zurücksetzen: Die Aktion erzeugt ein neues Passwort und zeigt es einmalig. Deine Zugangsdaten bleiben; nur wenn StartOS kein Passwort für dich gespeichert hat, stoppe BitcoinTX und führe Zugangsdaten festlegen vor dem nächsten Start aus. Du kommst von 1.2.1 oder älter? Öffne nach dem Update Settings > Ledger Review in BitcoinTX, und listet es Zahlen, die eine Neuberechnung ändern würde, führe Journal neu berechnen aus. Alles: ${CHANGELOG}`,
    pl_PL: `BitcoinTX 1.2.5 przynosi podgląd formularzy podatkowych na 2026 rok. Dopóki IRS nie opublikuje ostatecznych, Reports oferuje rok 2026 wypełniony na projektach IRS formularzy Form 8949 i Schedule D, oznaczonych na każdej stronie "DRAFT — DO NOT FILE": używaj ich do sprawdzenia swoich wartości, nigdy do złożenia. Podgląd kończy się sam 1 stycznia 2027; ostateczne formularze przyjdą w aktualizacji. Na telefonie panel dodawania lub edycji transakcji ma teraz przycisk zamknięcia (✕). Complete Tax Report nie ma już prawie zawsze pustej sekcji "Expenses"; wydatki pozostają w sekcji zysków kapitałowych, a żadna wartość się nie zmienia. Każdy składnik, z którego budowany jest BitcoinTX, jest teraz przypięty do dokładnej, zweryfikowanej wersji. Aktualizujesz z 1.2.4:0 lub starszej wersji? Ustaw dane logowania zastępuje Pokaż dane logowania i Zresetuj dane logowania: generuje nowe hasło i pokazuje je tylko raz. Twoje dane logowania zostają; tylko jeśli StartOS nie przechowuje dla ciebie hasła, zatrzymaj BitcoinTX i uruchom Ustaw dane logowania przed ponownym uruchomieniem. Aktualizujesz z 1.2.1 lub starszej wersji? Po aktualizacji otwórz Settings > Ledger Review w BitcoinTX, a jeśli pokazuje wartości, które zmieniłoby przeliczenie, uruchom Przelicz księgę. Wszystko: ${CHANGELOG}`,
    fr_FR: `BitcoinTX 1.2.5 apporte un aperçu des formulaires fiscaux de 2026. En attendant que l’IRS publie les versions définitives, Reports propose 2026 rempli sur les projets de l’IRS du Form 8949 et du Schedule D, marqués « DRAFT — DO NOT FILE » sur chaque page : servez-vous-en pour vérifier vos chiffres, jamais pour les déposer. L’aperçu s’arrête de lui-même le 1er janvier 2027 ; les formulaires définitifs arrivent dans une mise à jour. Sur un téléphone, le panneau d’ajout ou de modification d’une transaction a maintenant un bouton de fermeture (✕). Le Complete Tax Report n’a plus sa section « Expenses », presque toujours vide ; les dépenses restent dans la section des plus-values et aucun chiffre ne change. Chaque composant à partir duquel BitcoinTX est construit est désormais fixé à une version exacte et vérifiée. Vous venez de la 1.2.4:0 ou d’une version antérieure ? Définir les identifiants remplace Afficher les identifiants et Réinitialiser les identifiants : cette action génère un nouveau mot de passe et l’affiche une seule fois. Vos identifiants sont conservés ; seulement si StartOS ne garde aucun mot de passe pour vous, arrêtez BitcoinTX et lancez Définir les identifiants avant de le redémarrer. Vous venez de la 1.2.1 ou d’une version antérieure ? Après la mise à jour, ouvrez Settings > Ledger Review dans BitcoinTX et, s’il liste des chiffres qu’un recalcul changerait, lancez Recalculer le registre. Tout : ${CHANGELOG}`,
  },
  migrations: {
    up: async () => {},
    down: IMPOSSIBLE,
  },
})
