"""
The complete tax report: a tax year's holdings, capital gains, income and
balances, and the transactions behind them, as a PDF built with ReportLab
from reporting_core.generate_report_data().
"""

import datetime
import logging
from io import BytesIO
from typing import Any
from zoneinfo import ZoneInfo

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer

from backend.services.reports.pdf_layout import ReportStyles, grid_table
from backend.services.reports.safe_text import pdf_text

logger = logging.getLogger(__name__)

CONTENTS = (
    "1. Beginning of Year Holdings",
    "2. Capital Gains Summary",
    "3. Income Summary",
    "4. End of Year Balances",
    "5. Capital Gains/Losses Transactions",
    "6. Income Transactions",
    "7. Gifts, Donations & Lost Assets",
)

INCOME_TYPES = ("Income", "Reward", "Interest")


def generate_comprehensive_tax_report(report_dict: dict[str, Any]) -> bytes:
    """The PDF of `report_dict`, reporting_core.generate_report_data()'s
    result for one tax year."""
    report = _TaxReport(report_dict)
    story = [
        *report.title_page(),
        *report.beginning_of_year_holdings(),
        *report.capital_gains_summary(),
        *report.income_summary(),
        *report.end_of_year_balances(),
        *report.capital_gains_transactions(),
        *report.income_transactions(),
        *report.gifts_donations_lost(),
        Spacer(1, 0.5 * inch),
    ]
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=1.0 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )
    # The title page has no footer.
    doc.build(story, onLaterPages=_footer)
    logger.info(f"Generated comprehensive tax report for {report.year}")
    return buffer.getvalue()


def _footer(canvas: Canvas, doc) -> None:
    """Page numbers count from the page after the title page."""
    canvas.setFont("Helvetica", 9)
    canvas.drawString(0.5 * inch, 0.5 * inch, "Generated by BitcoinTX")
    canvas.drawRightString(7.75 * inch, 0.5 * inch, f"{doc.page - 1}")


def fmt_usd(value: float) -> str:
    return f"${value:,.2f}"


def fmt_btc(value: float) -> str:
    return f"{value:,.8f}"


def fmt_value(value) -> str:
    """A holding's market value; None when that day has no BTC price."""
    return "not priced" if value is None else fmt_usd(value)


class _TaxReport:
    """The report's sections, each a list of flowables."""

    def __init__(self, data: dict[str, Any]):
        self.data = data
        self.year = data.get("tax_year", "Unknown Year")
        self.tz = ZoneInfo(data.get("tax_timezone") or "UTC")
        self.styles = ReportStyles()

    def text(self, value: str, style=None) -> Paragraph:
        # Report data is text, never markup (safe_text.py)
        return Paragraph(pdf_text(value), style or self.styles.cell)

    def number(self, value: str) -> Paragraph:
        return self.text(value, self.styles.number)

    def heading(self, title: str) -> list:
        return [self.text(f"{self.year} {title}", self.styles.heading), Spacer(1, 0.1 * inch)]

    def date(self, iso: str) -> str:
        """An ISO 8601 timestamp as MM/DD/YYYY in the tax timezone, like the
        IRS forms."""
        if not iso:
            return ""
        try:
            moment = datetime.datetime.fromisoformat(iso.replace("Z", "+00:00"))
            if moment.tzinfo is None:
                moment = moment.replace(tzinfo=datetime.timezone.utc)
            return moment.astimezone(self.tz).strftime("%m/%d/%Y")
        except ValueError:
            return iso

    def title_page(self) -> list:
        normal = self.styles.normal
        notes = (
            "All fiat values and prices are in USD unless stated otherwise. "
            "Capital gains have been calculated using the FIFO accounting method. "
            "Trading between BTC and USD is treated as a taxable event. "
            "USD values are the ones entered with each transaction; a value left blank comes from "
            "that day's stored daily BTC price. All dates are shown in MM/DD/YYYY (IRS format), "
            f"in the tax timezone ({self.data.get('tax_timezone') or 'UTC'}). "
            "Capital gains from BTC with a holding period over 1 year are marked as Long Term gains; "
            "shorter periods are Short Term gains. This report may be used for tax purposes "
            "after verification by you or your tax advisor."
        )
        return [
            self.text(f"Tax Report {self.year}", self.styles.title),
            Spacer(1, 0.2 * inch),
            self.text(f"Date: {self.data.get('report_date', 'Unknown Date')}", normal),
            self.text(f"Period: {self.data.get('period', 'N/A')}", normal),
            Spacer(1, 0.2 * inch),
            self.text("Content", self.styles.heading),
            *[self.text(item, normal) for item in CONTENTS],
            Spacer(1, 0.2 * inch),
            self.text(notes, normal),
            self.text("Generated by BitcoinTX", normal),
            PageBreak(),
        ]

    def beginning_of_year_holdings(self) -> list:
        """All BTC held on January 1 as one row: quantity, average cost, value."""
        holdings = self.data.get("start_of_year_balances", [])
        story = self.heading("Beginning of Year Holdings")
        if not holdings:
            return story + [self.text("No data for beginning of year holdings", self.styles.normal),
                            Spacer(1, 0.5 * inch)]
        quantity = 0.0
        value = 0.0
        weighted_cost = 0.0
        for row in holdings:
            qty = row.get("quantity", 0.0)
            row_value = row.get("value")
            quantity += qty
            value = None if row_value is None or value is None else value + row_value
            weighted_cost += (qty * row.get("avg_cost_basis", 0.0))
        average_cost = weighted_cost / quantity if quantity > 0 else 0.0
        rows = [
            ["Quantity (BTC)", "Avg Cost Basis (USD)", "Value (USD)"],
            [self.number(fmt_btc(quantity)), self.number(fmt_usd(average_cost)), self.number(fmt_value(value))],
        ]
        story.append(grid_table(rows, [1.5, 1.5, 1.5]))
        if value is None:
            story.append(self.text(
                f"No BTC price is stored for {self.year}-01-01, so the holdings aren't valued "
                "(price lookups: Settings > Privacy & Network).",
                self.styles.normal,
            ))
        return story + [Spacer(1, 0.5 * inch)]

    def capital_gains_summary(self) -> list:
        # From the Form 8949 disposals (reporting_core._build_capital_gains_summary)
        summary = self.data.get("capital_gains_summary") or {}
        empty = {"proceeds": 0.0, "basis": 0.0, "gain": 0.0, "profits": 0.0, "losses": 0.0}
        short_term = {**empty, **summary.get("short_term", {})}
        long_term = {**empty, **summary.get("long_term", {})}
        rows = [
            ["Metric", "Short Term", "Long Term"],
            ["Number of Disposals", str(summary.get("number_of_disposals", 0)), ""],
        ]
        for label, key in (("Proceeds from Sales", "proceeds"), ("Acquisition Costs", "basis"),
                           ("Profits, Before Losses", "profits"), ("Losses", "losses"), ("Net Gains", "gain")):
            rows.append([label, fmt_usd(short_term[key]), fmt_usd(long_term[key])])
        return [
            *self.heading("Capital Gains Summary"),
            grid_table(rows, [2.5, 2, 2], columns=(1, -1)),
            Spacer(1, 0.5 * inch),
        ]

    def income_summary(self) -> list:
        totals = dict.fromkeys(("Income", "Interest", "Reward"), 0.0)
        for tx in self.data.get("income_transactions", []):
            if tx.get("asset") in ("BTC", "USD") and tx.get("type") in totals:
                totals[tx["type"]] += tx.get("value_usd", 0.0)
        rows = [["Source", "Amount (USD)"]]
        rows += [[source, fmt_usd(totals[source])] for source in INCOME_TYPES]
        rows.append(["Total", fmt_usd(totals["Income"] + totals["Reward"] + totals["Interest"])])
        return [
            *self.heading("Income Summary"),
            grid_table(rows, [2.5, 2.0], columns=(1, -1)),
            Spacer(1, 0.5 * inch),
        ]

    def end_of_year_balances(self) -> list:
        """Each BTC balance on December 31, with a total and the average cost."""
        balances = self.data.get("end_of_year_balances", [])
        story = self.heading("End of Year Balances")
        if not balances:
            return story + [self.text("No data for end of year balances", self.styles.normal),
                            Spacer(1, 0.5 * inch)]
        rows = [["Asset", "Quantity", "Cost (USD)", "Value (USD)", "Description"]]
        quantity = 0.0
        cost = 0.0
        value = 0.0
        for balance in balances:
            if not balance["asset"].startswith("BTC"):
                continue
            qty = balance.get("quantity", 0.0)
            balance_cost = balance.get("cost", 0.0)
            balance_value = balance.get("value")
            rows.append([
                self.text(balance["asset"]),
                self.number(fmt_btc(qty)),
                self.number(fmt_usd(balance_cost)),
                self.number(fmt_value(balance_value)),
                self.text(balance["description"]),
            ])
            quantity += qty
            cost += balance_cost
            value = None if balance_value is None or value is None else value + balance_value
        average_cost = cost / quantity if quantity > 0 else 0.0
        rows.append([
            "Total",
            self.number(fmt_btc(quantity)),
            self.number(fmt_usd(cost)),
            self.number(fmt_value(value)),
            self.text(f"Avg Cost Basis = {fmt_usd(average_cost)} per BTC"),
        ])
        return story + [grid_table(rows, [1.5, 1.2, 1.2, 1.2, 1.6], columns=(1, 3)), Spacer(1, 0.5 * inch)]

    def capital_gains_transactions(self) -> list:
        disposals = self.data.get("capital_gains_transactions", [])
        if not disposals:
            return []
        rows = [["Date Sold", "Date Acquired", "Asset", "Amount", "Cost (USD)", "Proceeds (USD)", "Gain/Loss",
                 "Holding"]]
        for tx in disposals:
            if tx.get("asset") == "BTC":
                rows.append([
                    self.text(self.date(tx.get("date_sold", ""))),
                    self.text(self.date(tx.get("date_acquired", ""))),
                    self.text("BTC"),
                    self.number(fmt_btc(tx.get("amount", 0.0))),
                    self.number(fmt_usd(tx.get("cost", 0.0))),
                    self.number(fmt_usd(tx.get("proceeds", 0.0))),
                    self.number(fmt_usd(tx.get("gain_loss", 0.0))),
                    self.text(tx.get("holding_period", "")),
                ])
        return [
            *self.heading("Capital Gains/Losses Transactions"),
            grid_table(rows, [1.0, 1.0, 0.6, 0.8, 0.8, 0.8, 0.8, 0.8], columns=(3, 6)),
            Spacer(1, 0.5 * inch),
        ]

    def income_transactions(self) -> list:
        income = self.data.get("income_transactions", [])
        if not income:
            return []
        rows = [["Date", "Asset", "Amount", "Value (USD)", "Type", "Description"]]
        for tx in income:
            if tx.get("asset") in ("BTC", "USD"):
                rows.append([
                    self.text(self.date(tx.get("date", ""))),
                    self.text(tx["asset"]),
                    self.number(fmt_btc(tx.get("amount", 0.0))),
                    self.number(fmt_usd(tx.get("value_usd", 0.0))),
                    self.text(tx.get("type", "")),
                    self.text(tx.get("description", "")),
                ])
        return [
            *self.heading("Income Transactions"),
            grid_table(rows, [1.0, 0.6, 0.8, 0.8, 0.8, 2.2], columns=(2, 3)),
            Spacer(1, 0.5 * inch),
        ]

    def gifts_donations_lost(self) -> list:
        """Withdrawals that aren't sales: their proceeds are $0; the fair
        market value is the one entered with the transaction."""
        items = self.data.get("gifts_donations_lost", [])
        if not items:
            return []
        rows = [["Date", "Asset", "Amount", "Proceeds (USD)", "FMV (USD)", "Type"]]
        for item in items:
            if item.get("asset") == "BTC":
                fmv = item.get("fmv_usd")
                rows.append([
                    self.text(self.date(item.get("date", ""))),
                    self.text("BTC"),
                    self.number(fmt_btc(item.get("amount", 0.0))),
                    self.number(fmt_usd(item.get("proceeds_usd", 0.0))),
                    self.number(fmt_usd(fmv) if fmv is not None else "not given"),
                    self.text(item.get("type", "")),
                ])
        return [
            *self.heading("Gifts, Donations & Lost Assets"),
            grid_table(rows, [1.0, 0.8, 0.9, 0.9, 0.9, 1.3], columns=(2, 4)),
            Spacer(1, 0.5 * inch),
        ]
